### ISSUE TITLE
Bolloom Buds dont render in the corner of the screen

### ISSUE THREAD

**Issue by five0five** [SnappyDragon18/Endergetic#1]
title says it all, applies only to the block and not to the entities

**Comment by SmellyModder** [comment]
This is most likely caused due to the TESR(Tile Entity Special Renderer) only wanting to render the bud when the block is in view of the player's camera. This is possibly fixable and I'll look into it.

**Comment by SmellyModder** [comment]
Ok so I've fixed it slightly. I can't fix it fully since the bud's pedals aren't actual blocks that are there but I've made it not render them only if you're very close to the edge of it's view.
