### ISSUE TITLE
Poise Cluster levitating is only triggered by normal arrows

### ISSUE THREAD

**Issue by five0five** [SnappyDragon18/Endergetic#2]
Poise Cluster blocks only levitate when hit with default arrows and don't work with arrows variants, tridents or other projectiles like snowballs, additionally, it only works when hit from the side, but that might be intentional?

**Comment by SmellyModder** [comment]
Them only working for the side is intentional. And yeah I was thinking about making all projectiles work against them.

**Comment by SmellyModder** [comment]
Alright I've made them able to be hit with Tridents and all arrow types. As for the top hitting not working this is intentional.

**Comment by five0five** [comment]
Maybe check whether the projectile is able to deal damage to entities? I feel like this would make them integrate with other mods' projectiles better while avoiding snowballs and such being able to trigger them.
