### ISSUE TITLE
Poise Trapdoor makes block above it dissappear 

### ISSUE THREAD

**Issue by five0five** [SnappyDragon18/Endergetic#4]
this happens when you place the trapdoor, blocks can be placed on top of it afterwards

**Comment by SmellyModder** [comment]
See if this happens with vanilla forge trapdoors as well

**Comment by SmellyModder** [comment]
Nvm I tested it myself and yeah vanilla forge ones do not do this

**Comment by SmellyModder** [comment]
Fixed
