### ISSUE TITLE
Advancements gained from killing bolloom/poise entities

### ISSUE THREAD

**Issue by five0five** [SnappyDragon18/Endergetic#5]
For example, the advancement "a throwaway joke" (hit a mob with a trident) can be achieved from hitting bolloom entities and moving poise entities. This can't be achieved when hitting eg. a minecart as the advancement is only supposed to work with mobs.

**Comment by five0five** [comment]
Forgot to mention, this also applies to things like "take aim" and that advancement was merely an example.

**Comment by SmellyModder** [comment]
This is intentional
